// Copy the built guides into public/ so the GUI can serve them (and link into
// their exact sections via #nameddest=).  Runs on predev + prebuild.  The PDFs
// are LaTeX build artifacts (docs/Makefile); we don't commit the copies.
import { mkdirSync, copyFileSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const dstDir = resolve(here, "../public/docs");
mkdirSync(dstDir, { recursive: true });

//  WHICH GUIDES ARE PUBLIC IS DECIDED IN ONE PLACE: `DOCS` in docs/Makefile.
//
//  It used to be decided in three -- there, here, and again in the allowlist
//  inside gui/public/guide.html -- and the three had drifted apart from the
//  tree they describe: docs/ carries .tex AND .pdf for designGuide,
//  explorerGuide and tutorialsGuide, none of which `make all` builds and none
//  of which the app can open.  Three manuals that exist and are unreachable,
//  which is the arity sin with a reader on the other end of it.
//
//  So this PARSES the Makefile's own assignment and REFUSES if it cannot find
//  it.  A build that silently fell back to a hardcoded list would recreate the
//  second home this exists to remove -- and it would do it at the exact moment
//  the two had diverged, which is the only moment it matters.
const makefile = resolve(here, "../../docs/Makefile");
const docsLine = /^DOCS\s*:=\s*(.+)$/m.exec(readFileSync(makefile, "utf8"));
if (!docsLine) {
  console.error("[copyDocs] cannot find the `DOCS :=` assignment in docs/Makefile -- "
              + "that line is the one home for which guides are public, and without it "
              + "this script would have to invent the list.  Refusing.");
  process.exit(1);
}
const guides = docsLine[1].trim().split(/\s+/);

//  The DISPLAY LABEL is this file's to own -- the Makefile has no business
//  carrying UI strings.  A guide in DOCS with no title REFUSES rather than
//  appearing in the app under its bare key: an unlabelled entry in a reader's
//  menu is a defect they cannot report usefully.
//
//  THE LABEL IS THE GUIDE'S OWN TITLE, not a table kept here.  This used to
//  be a hand-written LABELS map, and seven of its eight entries reproduced
//  the guide's `\docTitle` exactly -- while the eighth said "Design Guide"
//  where docs/designGuide.tex declares **Process Design Heuristics**.  So
//  the one guide whose subject the reader was hunting for (heuristics,
//  rules of thumb) was the one whose menu entry did not say what it is.
//  A second home for a title drifts on the entry that matters most.
const LABELS = Object.fromEntries(guides.map((g) => {
  const tex = resolve(here, "../../docs", `${g}.tex`);
  const m = existsSync(tex)
    && /\\newcommand\{\\docTitle\}\{([^}]*)\}/.exec(readFileSync(tex, "utf8"));
  return [g, m ? m[1].trim() : null];
}));
const unlabelled = guides.filter((g) => !LABELS[g]);
if (unlabelled.length > 0) {
  console.error(`[copyDocs] no \\docTitle in docs/<guide>.tex for: ${unlabelled.join(", ")}`
              + " -- a guide the app lists under its bare key looks like a bug to the"
              + " reader and cannot be reported as one.  Add \\newcommand{\\docTitle}{...}"
              + " to the .tex, which is the one place a guide's title belongs.");
  process.exit(1);
}

for (const guide of guides) {
  const name = `${guide}.pdf`;
  const src = resolve(here, "../../docs", name);
  if (!existsSync(src)) {
    console.warn(`[copyDocs] ${name} missing — run 'make' in docs/ first; its in-app links will 404.`);
    continue;
  }
  copyFileSync(src, resolve(dstDir, name));
  console.log(`[copyDocs] ${name} -> public/docs/`);
}

//  The Rules-of-Thumb INDEX the EduTool page fetches.  A build artefact
//  beside the PDFs, exactly like guides.json -- not a second source: it is
//  regenerated by bin/curate/design_guide_index.py from docs/designGuide.tex
//  and carries titles and labels only, no rule text.  A page may FETCH (a
//  menu may not, which is why guides.generated.ts exists as well).
const rotSrc = resolve(here, "../../generated/designGuideIndex.json");
if (existsSync(rotSrc)) {
  copyFileSync(rotSrc, resolve(dstDir, "designGuideIndex.json"));
  console.log("[copyDocs] designGuideIndex.json -> public/docs/");
} else {
  console.warn("[copyDocs] generated/designGuideIndex.json missing --"
             + " run bin/curate/design_guide_index.py; the Rules of Thumb"
             + " page will have nothing to show.");
}

//  The manifest guide.html reads.  Derived here, never hand-written there.
writeFileSync(resolve(dstDir, "guides.json"),
  JSON.stringify(Object.fromEntries(guides.map((g) => [g, LABELS[g]])), null, 2) + "\n");

//  ...AND THE SAME LIST FOR THE HELP MENU, because the menu had its own.
//
//  `guides.json` lands in public/ and is fetched at runtime, which serves
//  guide.html perfectly and serves a MENU not at all -- a menu cannot wait
//  for a fetch to know what it contains.  So the menu kept a hand-written
//  four (`GuideName` was literally a union of four string literals, and the
//  comment above it said "The four glass-box manuals").  DOCS grew to eight.
//  The Design Guide -- 2400 lines of heuristics and rules of thumb -- was
//  built, copied, published to the site, and reachable from nowhere in the
//  app.  The owner reported it as DELETED, which is what an unreachable
//  document looks like from outside.
//
//  This emits the same list as a TypeScript module the menu imports at build
//  time.  It is committed so a clean `npm run typecheck` (which does not run
//  prebuild) still compiles, and check_guide_menu.py fails when it drifts
//  from docs/Makefile.
const ts = [
  "//  GENERATED by gui/scripts/copyDocs.mjs from `DOCS` in docs/Makefile.",
  "//  DO NOT EDIT.  Adding a guide to DOCS and a label to copyDocs' LABELS",
  "//  is what puts it in the Help menu; there is no second list to update,",
  "//  which is the whole point -- see check_guide_menu.py.",
  "",
  "export const GUIDES = [",
  ...guides.map((g) => `    { name: "${g}", label: ${JSON.stringify(LABELS[g])} },`),
  "] as const;",
  "",
  "export type GuideName = (typeof GUIDES)[number][\"name\"];",
  "",
].join("\n");
const tsPath = resolve(here, "../src/help/guides.generated.ts");
if (!existsSync(tsPath) || readFileSync(tsPath, "utf8") !== ts) {
  writeFileSync(tsPath, ts);
  console.log("[copyDocs] src/help/guides.generated.ts -> regenerated");
}
console.log(`[copyDocs] guides.json -> ${guides.length} guide(s): ${guides.join(", ")}`);

// ---------------------------------------------------------------------------
//  The pdf.js runtime that guide.html draws with.
//
//  Staged the same way as the PDFs and for the same reason: it is an
//  installed artifact, not source, so it is gitignored and re-staged on every
//  predev/prebuild.  guide.html loads these by ABSOLUTE-ish URL relative to
//  its own location (`pdfjs/pdf.min.mjs`), so the layout under public/pdfjs/
//  is part of that page's contract -- change one, change the other.
//
//  A CHECK THAT CANNOT RUN MUST NOT PASS: if pdfjs-dist is not installed the
//  guides would silently stop opening, so this REFUSES rather than warns.
const pdfjsSrc = resolve(here, "../node_modules/pdfjs-dist");
if (!existsSync(pdfjsSrc)) {
  console.error("[copyDocs] pdfjs-dist is not installed -- guide.html cannot draw the "
              + "manuals, and Help would open nothing.  Run: npm install");
  process.exit(1);
}
const pdfjsDst = resolve(here, "../public/pdfjs");
mkdirSync(pdfjsDst, { recursive: true });
for (const [from, to] of [
  ["build/pdf.min.mjs",        "pdf.min.mjs"],         // the core library
  ["build/pdf.worker.min.mjs", "pdf.worker.min.mjs"],  // parsing/rendering worker
  ["web/pdf_viewer.mjs",       "pdf_viewer.mjs"],      // viewer components (nameddest, text layer)
  ["web/pdf_viewer.css",       "pdf_viewer.css"],
  //  pdf_viewer.css names this as a background-image, so every guide tab
  //  fetched it and got a 404 on the published site (measured 2026-09-02).
  //  Cosmetic -- but a 404 in the console of a page whose whole job is to
  //  reassure the reader that Help works is not nothing.
  ["web/images/loading-icon.gif", "images/loading-icon.gif"],
]) {
  mkdirSync(dirname(resolve(pdfjsDst, to)), { recursive: true });
  copyFileSync(resolve(pdfjsSrc, from), resolve(pdfjsDst, to));
}
console.log("[copyDocs] pdf.js runtime -> public/pdfjs/");
