/*---------------------------------------------------------------------------*\
       \|/       C hemicals     | Open-source, glass-box chemical process simulator
      \\|//      H eat-transfer | https://choupo.org
     \\\|///     O perations    |
      \\|//      U nits         | Copyright (C) 2026 Vítor Geraldes
       \|/       P roperties    | Licence: GPL-3.0-or-later
        |        O ptimization  |
       /|\                      |
-------------------------------------------------------------------------------
    SPDX-License-Identifier: GPL-3.0-or-later
    Credit and attribution: see AUTHORS
    Required legal notices:  see NOTICE
\*---------------------------------------------------------------------------*/

/*---------------------------------------------------------------------------*\
  elementPotentialLesson -- HOW a Gibbs reactor SOLVES (commission C15,
  2026-09-27).  Not what a Gibbs reactor IS: that, and the collapse of N
  amounts into one potential per element, is the `claus-gibbs` page, and
  this one links to it rather than becoming a second home for it.

  EVERY ENGINE CLAIM CARRIES A file:line, READ at that line on 2026-09-27 and
  held there by tests/elementPotentialLesson.test.ts (the numericsLessons
  ANCHORS precedent: a citation whose line moves under it fails the test).
  EVERY NUMBER IN THE PROSE comes from `EP_QUOTED` below, and the same test
  recomputes each one from the witnesses' own `newtonLog` files, generated by
  THIS tree's engine before the test runs (tests/witnessOutputs.ts).  So the
  page goes red the day the engine moves a digit it prints -- which is the
  point of quoting numbers at all.
\*---------------------------------------------------------------------------*/

import type { LessonStep, LessonLimit } from "./lessonStep.js";
export type { LessonStep, LessonLimit };

/** The numbers the prose quotes, each as the page prints it.  Every entry is
 *  recomputed from the engine's own log by the test, to the digits shown --
 *  a second home for a number is tolerable only when something holds the two
 *  together. */
export const EP_QUOTED = {
  // --- shift reactor, 800 K, 1 bar (gibbs12 `shift`, gibbs01's problem)
  shiftIterations: 6,
  shiftSeedLnnCO: "-8.89",         // ln n_CO at the least-squares seed
  shiftSeedNormF: "0.499",         // |F| at iteration 0, mol/s
  shiftFirstAlpha: "1/64",         // the first backtracking factor, 0.015625
  shiftNormF: ["0.235", "0.142", "0.0147", "2.06e-4", "4.25e-8", "3.0e-15"],
  shiftPiC: "0.8342", shiftPiH: "-9.0348", shiftPiO: "-44.3142",
  shiftLnN: "-1.2809",
  shiftGRT: { CO: "-41.6726", water: "-60.5764", CO2: "-86.7032", H2: "-16.9786" },
  shiftLnY: { CO: "-1.8073", water: "-1.8073", CO2: "-1.0909", H2: "-1.0909" },
  shiftLnK: "1.433",
  shiftK: "4.19",
  // --- gibbs07 at 350 K: the liquid
  liquidYP: "50001",               // y_water P on the gas-only answer, Pa
  liquidPsat: "42169",             // Psat_water(350 K), Pa
  liquidSolves: 38,                // fluid solves the search on L made
  liquidL: "0.03762",              // mol/s
  // --- coking reactor, 1000 K, S/C 0.8 (gibbs11's reformerLow)
  cokingPiC: "-0.6765",
  cokingGRT: "-1.5224",            // g_graphite / RT
  cokingLnA: "0.8459",
  cokingA: "2.33",
  cokingSolves: 37,
  cokingNs: "0.0690",              // mol/s of graphite
  // --- ammonia reactor, 700 K, 5 bar (equil03's feed)
  ammoniaSeedLnnWater: "17.47",
  ammoniaSeedLnnN2: "13.48",
  ammoniaSeedNWater: "3.9 × 10⁷",  // exp(ammoniaSeedLnnWater), mol/s
  ammoniaSeedNN2: "7.1 × 10⁵",     // exp(ammoniaSeedLnnN2), mol/s
  ammoniaSeedNormF: "9.47e7",
  ammoniaPrimalIterations: 18,
  ammoniaReseedNormF: "1.0e-13",
  ammoniaReseedIterations: 0,
} as const;

const Q = EP_QUOTED;

export const EP_STEPS: readonly LessonStep[] = [
  {
    n: 1,
    title: "N amounts become M + 1 unknowns",
    body: "The page `The allotrope nobody declared` derives why a constrained "
      + "minimum of G attaches one multiplier to each ELEMENT, and how that "
      + "turns every species amount into a closed form.  This page starts "
      + "where that one stops: from the closed form, what does the engine "
      + "actually SOLVE?  Not the amounts.  It solves for one element "
      + "potential per element and the logarithm of the total, and builds "
      + "every amount from them (the residual, GibbsMethod.cpp:76–94).  On "
      + "the witness, the water-gas shift reactor carries four species over "
      + "three elements (C, H, O): four unknowns, π_C, π_H, π_O and ln N.  "
      + "The steam reformer beside it carries six species and still has "
      + "four unknowns — the number is set by the ELEMENTS, never by the "
      + "species list.",
    derivation: [
      { step: "At the constrained minimum every species present satisfies "
          + "its stationarity condition, derived on the Claus page: its "
          + "chemical potential over RT equals the sum of its atoms' element "
          + "potentials.",
        eq: String.raw`\frac{g^\circ_i(T)}{RT} + \ln\frac{y_i\,P}{P^\circ} = \sum_k \pi_k A_{ki}` },
      { step: "Write y_i = n_i / N and solve for the amount.  This is the "
          + "change of variables: n_i is no longer an unknown, it is a "
          + "function of the M + 1 unknowns.",
        eq: String.raw`n_i(\pi, N) = \exp\!\left(\ln N - \ln\frac{P}{P^\circ} - \frac{g^\circ_i}{RT} + \sum_k \pi_k A_{ki}\right)` },
      { step: "Substitute into what is still unmet: the M element balances "
          + "and the definition of N.  That is M + 1 equations in M + 1 "
          + "unknowns, which the Newton of the next step solves.",
        eq: String.raw`f_k = \sum_i A_{ki}\,n_i - b_k = 0, \qquad f_{M+1} = \sum_i n_i - N = 0` },
    ],
    formula: String.raw`x = \left(\pi_1, \ldots, \pi_M, \ln N\right), \qquad F(x) = \left(f_1, \ldots, f_M, f_{M+1}\right) = 0`,
    where: [
      { sym: "g^\\circ_i", means: "the standard-state molar Gibbs energy of "
        + "species i at T, on the elements datum — `g_pure_ig` in the engine",
        unit: "J/mol" },
      { sym: "R", means: "the gas constant", unit: "J/(mol·K)" },
      { sym: "T", means: "the reactor temperature", unit: "K" },
      { sym: "y_i", means: "the mole fraction of species i in the gas" },
      { sym: "P", means: "the reactor pressure", unit: "Pa" },
      { sym: "P^\\circ", means: "the standard pressure of the formation "
        + "data, 1 bar", unit: "Pa" },
      { sym: "\\pi_k", means: "the ELEMENT POTENTIAL of element k: the "
        + "Lagrange multiplier of its balance, divided by RT — one per "
        + "element, an unknown of the Newton" },
      { sym: "\\pi", means: "the vector of all M element potentials" },
      { sym: "A_{ki}", means: "the atom matrix: atoms of element k in "
        + "species i, the `atoms ( ... )` list the case declares",
        unit: "atoms per molecule" },
      { sym: "n_i", means: "the amount of species i in the gas", unit: "mol/s" },
      { sym: "N", means: "the total amount — an UNKNOWN of the Newton, "
        + "equal to the sum of the n_i only once the last residual is zero",
        unit: "mol/s" },
      { sym: "f_k", means: "the residual of element k's balance",
        unit: "mol/s of atoms" },
      { sym: "b_k", means: "the feed's atoms of element k", unit: "mol/s" },
      { sym: "f_{M+1}", means: "the residual of the total: the sum of the "
        + "amounts minus N", unit: "mol/s" },
      { sym: "M", means: "the number of elements" },
      { sym: "\\pi_M", means: "the element potential of the last, M-th, "
        + "element" },
      { sym: "f", means: "one residual of F; f_1 to f_M are the element "
        + "balances in the order the case declares its elements",
        unit: "mol/s" },
      { sym: "f_M", means: "the residual of the M-th element's balance",
        unit: "mol/s of atoms" },
      { sym: "x", means: "the Newton's unknown vector: the M element "
        + "potentials and ln N" },
      { sym: "F", means: "the vector of the M + 1 residuals" },
    ],
    note: "WHAT THE CHANGE OF VARIABLES BUYS.  Every species' stationarity "
      + "condition holds BY CONSTRUCTION, at every iterate, whatever the "
      + "Newton is doing — it is the formula the amounts are built from.  "
      + "What the Newton must still achieve is only that the atoms balance "
      + "and that N is the true total.  N stationarity equations have "
      + "disappeared into the parameterisation, which is why the system "
      + "stays at M + 1 however many species you declare.",
  },
  {
    n: 2,
    title: "The Newton, iteration by iteration",
    body: "The engine solves F(x) = 0 with its general Newton (solver/"
      + "NewtonND.cpp): a finite-difference Jacobian (NewtonND.cpp:477), one "
      + "Gauss elimination for the step (:479), then a line search that "
      + "halves the step until |F| falls (:491–512).  It stops when "
      + "|F| < 10⁻⁸ mol/s, within 80 iterations (GibbsMethod.cpp:128–129).  "
      + "It starts from a least-squares fit of the potentials that pretends "
      + "the FEED is already the answer (GibbsMethod.cpp:100–124).  On the "
      + `shift reactor at 800 K that seed puts CO at ln n = ${Q.shiftSeedLnnCO}: `
      + "about 1.4 × 10⁻⁴ mol/s against 0.139 fed, so every balance is "
      + `short and |F| = ${Q.shiftSeedNormF} mol/s.  The full Newton step `
      + "from there does not reduce |F|, so the line search halves it to "
      + `α = ${Q.shiftFirstAlpha}; from the next iterate on every full step `
      + `is accepted and |F| falls ${Q.shiftNormF.join(", ")} mol/s — `
      + `converged in ${Q.shiftIterations} iterations, the digits doubling `
      + "at the end, which is what a Newton does near its root.  Read ln N "
      + "in the table below: it does not move, because CO + H₂O → CO₂ + H₂ "
      + "neither makes nor destroys moles.",
    formula: String.raw`J\!\left(x^{(j)}\right)\Delta x^{(j)} = -F\!\left(x^{(j)}\right), \qquad x^{(j+1)} = x^{(j)} + \alpha_j\,\Delta x^{(j)}`,
    where: [
      { sym: "J", means: "the Jacobian of F: how each residual moves when "
        + "each unknown moves, formed by finite differences" },
      { sym: "\\Delta x", means: "the full Newton step, from one linear "
        + "solve" },
      { sym: "\\alpha_j", means: "the backtracking factor of iteration j: 1 "
        + "for the full step, halved until |F| decreases" },
      { sym: "j", means: "the iteration counter" },
    ],
    note: "WHY NO AMOUNT CAN EVER GO NEGATIVE.  The Newton moves π and ln N, "
      + "never an amount.  Every n_i is an exponential of a real number, so "
      + "it is positive at every iterate, however wild the step — a Newton "
      + "on the amounts themselves can step straight through zero and has "
      + "to be caged.  The price is the other end: a species the "
      + "thermodynamics disfavours is not zero but tiny (the ammonia left "
      + "in step 5's outlet is e⁻⁵⁶ mol/s), and the residual caps each "
      + "exponent at e^±50 so a wild trial cannot overflow "
      + "(GibbsMethod.cpp:51–52, :84).  The published amounts are not "
      + "capped (GibbsMethod.cpp:313), and if the upper cap binds at the "
      + "answer the run says so.",
  },
  {
    n: 3,
    title: "What the element potentials mean at the answer",
    body: "At the answer the Newton has made the atoms balance and N the "
      + "true total, so y_i = n_i / N is the real composition and the "
      + "stationarity condition of step 1 becomes a statement about the "
      + "outlet: every species' chemical potential is the sum of its "
      + "atoms' potentials.  The engine publishes λ_k = π_k R T as the KPI "
      + "`lambda_<element>` (GibbsReactor.cpp:676).  Check it by hand on "
      + `the shift answer: π_C = ${Q.shiftPiC}, π_H = ${Q.shiftPiH}, `
      + `π_O = ${Q.shiftPiO}.  For CO, g°/RT = ${Q.shiftGRT.CO} and `
      + `ln y = ${Q.shiftLnY.CO} (P = 1 bar, so ln P/P° = 0): their sum is `
      + "the chemical potential over RT, and π_C + π_O gives the same "
      + "number.  The table below the panel does it for every species.  "
      + "Then subtract: any reaction among these species conserves atoms, "
      + "so its Σ ν μ is Σ ν Σ π A = 0 — every reaction is at equilibrium "
      + "at once, with no reaction ever declared.  For the shift, "
      + `ln K = −Σ ν g°/RT = ${Q.shiftLnK}, K = ${Q.shiftK}, and the `
      + "outlet's y_CO₂ y_H₂ / (y_CO y_H₂O) is the same number.",
    formula: String.raw`\frac{\mu_i}{RT} = \frac{g^\circ_i}{RT} + \ln\frac{y_i\,P}{P^\circ} = \sum_k \pi_k A_{ki}, \qquad \lambda_k = \pi_k R T`,
    where: [
      { sym: "\\mu_i", means: "the chemical potential of species i in the "
        + "outlet gas", unit: "J/mol" },
      { sym: "\\nu_i", means: "the stoichiometric coefficient of species i "
        + "in a reaction: negative for a reactant, positive for a product" },
      { sym: "K", means: "the equilibrium constant of that reaction at T, "
        + "on the ideal-gas rung, exp(−Σ ν g°/RT)" },
      { sym: "\\lambda_k", means: "the element potential of element k in "
        + "energy units: the Gibbs energy one mole of its atoms carries in "
        + "this mixture — published as the KPI `lambda_<element>`",
        unit: "J/mol" },
    ],
    derivation: [
      { step: "Multiply the stationarity condition of each species by its "
          + "stoichiometric coefficient in any reaction and add.",
        eq: String.raw`\sum_i \nu_i \frac{\mu_i}{RT} = \sum_k \pi_k \sum_i \nu_i A_{ki}` },
      { step: "A reaction conserves every element, so the inner sum is zero "
          + "for every k, and the left side is the reaction's own "
          + "equilibrium condition.",
        eq: String.raw`\sum_i \nu_i A_{ki} = 0 \quad\implies\quad \ln K = -\sum_i \nu_i \frac{g^\circ_i}{RT} = \sum_i \nu_i \ln\frac{y_i\,P}{P^\circ}` },
    ],
    note: "WHY THIS IS A CHECK AND NOT A TAUTOLOGY.  The identity holds at "
      + "every iterate with y_i = n_i / N — but N is an unknown, and before "
      + "convergence the amounts do not add up to it, so that y is the "
      + "composition of no real mixture.  Only at the answer is it the "
      + "outlet the reactor publishes, and only there does the hand check "
      + "on the published mole fractions close.",
  },
  {
    n: 4,
    title: "A new phase: tested on the gas answer, then found by a search",
    body: "Neither a liquid nor a solid makes the Newton bigger.  The engine "
      + "solves the gas alone, TESTS whether a new phase would lower G, and "
      + "only then SEARCHES for how much of it forms — a one-dimensional "
      + "bisection, each step of which is a whole gas Newton.  The LIQUID, "
      + "on gibbs07 (1 CO : 3 steam at 350 K): the test compares y_i P with "
      + "Psat_i for every species with a vapour pressure "
      + `(ElementPotential.cpp:58–66); water is at ${Q.liquidYP} Pa against `
      + `Psat(350 K) = ${Q.liquidPsat} Pa, supersaturated.  The engine fixes `
      + "the liquid amount L, solves the gas on the atoms that remain, and "
      + "bisects L until the gas leaves exactly saturated "
      + `(ElementPotential.cpp:79–114): ${Q.liquidSolves} gas solves, `
      + `L = ${Q.liquidL} mol/s.  The SOLID, on the witness's steam-lean `
      + "reformer at 1000 K: graphite has no mole fraction — it is its own "
      + "phase at activity one — so the test is its activity in the "
      + "graphite-free gas (GibbsSolidPhase.cpp:105, :231): "
      + `π_C − g_C/RT = ${Q.cokingPiC} − (${Q.cokingGRT}) = ${Q.cokingLnA}, `
      + `a_C = ${Q.cokingA} > 1, so depositing carbon lowers G.  The engine `
      + "then bisects the deposited amount between zero and the point where "
      + "the gas runs out of carbon (GibbsSolidPhase.cpp:259–310), each "
      + `trial a gas Newton on the atoms left: ${Q.cokingSolves} gas solves, `
      + `${Q.cokingNs} mol/s of graphite, and a_C back to 1.`,
    formula: String.raw`y_c\,P = P^\mathrm{sat}_c \quad\text{(liquid present)}, \qquad \ln a_s = \sum_k \pi_k A_{ks} - \frac{g^\circ_s}{RT} = 0 \quad\text{(solid present)}`,
    where: [
      { sym: "y_c", means: "the gas mole fraction of the one condensing "
        + "species" },
      { sym: "P^\\mathrm{sat}_c", means: "its vapour pressure at T, from "
        + "its own record", unit: "Pa" },
      { sym: "a_s", means: "the activity of the pure solid s that the gas "
        + "implies: above one, depositing s lowers G" },
      { sym: "A_{ks}", means: "the atoms of element k in the solid s (for "
        + "graphite, one carbon)", unit: "atoms per formula unit" },
      { sym: "g^\\circ_s", means: "the standard Gibbs energy of the pure "
        + "solid at T, on the solid rung", unit: "J/mol" },
    ],
    note: "BOTH TESTS ARE THE SAME TEST.  A phase belongs at the minimum "
      + "exactly when its own chemical potential, read off the element "
      + "potentials, is no LOWER than its standard state (the solid's ln a_s ≥ "
      + "0) — the liquid's "
      + "through Raoult (y_c P = Psat_c), the solid's through a_s = 1.  The "
      + "element potentials price a phase the gas does not yet contain, "
      + "and that is what makes the test possible without solving anything "
      + "new.",
  },
  {
    n: 5,
    title: "Where the method fails: the seed is part of the method",
    body: "Ten per cent ammonia in air at 700 K and 5 bar.  The "
      + "least-squares seed pretends the feed is the answer, and this feed "
      + "is as far from its answer as a feed can be: it holds no water at "
      + "all and must leave with 15 % of it.  The fit hands that whole "
      + "affinity to the potentials, and the seed puts water at "
      + `ln n = ${Q.ammoniaSeedLnnWater} and nitrogen at `
      + `${Q.ammoniaSeedLnnN2} — ${Q.ammoniaSeedNWater} and `
      + `${Q.ammoniaSeedNN2} mol/s against 27.8 mol/s fed, `
      + `|F| = ${Q.ammoniaSeedNormF} mol/s.  Two species then carry every `
      + "atom (water all the hydrogen and oxygen, nitrogen all the "
      + "nitrogen), every column of the 4 × 4 Jacobian is dominated by the "
      + "same two directions, and the Gauss elimination meets a zero pivot "
      + "at iteration 0 — the Newton stops without taking a step "
      + "(NewtonND.cpp:479–488).  The engine does not give up and does not "
      + "stay silent: it re-seeds (GibbsMethod.cpp:230–289) from a PRIMAL "
      + "Newton on ln n_i started from equal amounts of every species (the "
      + "reduced equations of Gordon & McBride, NASA RP-1311, "
      + "GibbsMethod.cpp:409–533), whose matrix is weighted by the current "
      + "amounts and whose steps are limited so no major species changes by "
      + `more than a factor e² at once (:519).  It takes ${Q.ammoniaPrimalIterations} `
      + "primal iterations and hands the element-potential Newton a start "
      + `where |F| = ${Q.ammoniaReseedNormF} mol/s — already under the 10⁻⁸ `
      + "tolerance, so the Newton converges in "
      + `${Q.ammoniaReseedIterations} iterations.  On this feed the primal `
      + "iteration is the solver and the element-potential Newton is the "
      + "check; the run log and its caveat block say which route answered.",
    formula: String.raw`\Delta\ln n_i = -\frac{\mu_i}{RT} + \sum_k \pi_k A_{ki} + \Delta\ln N`,
    where: [
      { sym: "\\Delta\\ln n_i", means: "the primal step: the change in the "
        + "logarithm of species i's amount in one primal iteration" },
      { sym: "\\Delta\\ln N", means: "the change in the logarithm of the "
        + "total in the same iteration" },
    ],
    note: "A NEWTON'S SEED IS PART OF THE METHOD.  The element-potential "
      + "equations are the same at 700 K and at 1100 K; what changes is "
      + "whether the point the Newton starts from can see its own answer.  "
      + "Move the temperature knob up and read the route table: above a "
      + "certain temperature the least-squares seed converges on its own, "
      + "below it the re-seed answers.  The answer is the same Newton's "
      + "either way, on the same residual, to the same tolerance.",
  },
];

export const EP_LIMITS: readonly LessonLimit[] = [
  {
    id: "outermost-solve-only",
    title: "The log traces the outermost Newton; the phase searches are counted, not traced.",
    body: "Each fluid solve inside a liquid or solid bisection is a complete "
      + "element-potential Newton, and the log records its result — the "
      + "amount tried and the residual it left — not its iterations.  In "
      + "adiabatic mode the log covers only the final solve at the converged "
      + "temperature; the outer Newton's trial temperatures are not logged.",
  },
  {
    id: "one-condensable",
    title: "One condensing species, and the method says nothing when there are two.",
    body: "The element-potential method adds a liquid of ONE pure "
      + "condensable.  With two species supersaturated at once it returns "
      + "the gas-only answer (ElementPotential.cpp:71) and the run does not "
      + "announce it; the reactiveFlash and directMin methods carry a "
      + "multi-component liquid.  Two pure solids supersaturated at once are "
      + "REFUSED by name.",
  },
  {
    id: "liquid-energy-debt",
    title: "The condensing reactor's energy balance does not close.",
    body: "gibbs07, whose Newton and liquid search step 4 reads, is a pinned "
      + "open debt of the plant-boundary first law "
      + "(check_energy_closure.KNOWN_OPEN).  The page reads its equilibrium, "
      + "which is not in question, and not its duty.",
  },
  {
    id: "ideal-gas",
    title: "Ideal gas throughout.",
    body: "Every witness here declares `fugacityModel idealGas`.  Under a "
      + "real equation of state the engine folds ln φ_i into g°/RT and "
      + "repeats the Newton until φ settles (GibbsMethod.cpp:66–74); those "
      + "passes are logged as `warmStartPass` stages and are not on this "
      + "page.",
  },
  {
    id: "no-rate",
    title: "Equilibrium is not conversion.",
    body: "Nothing here says how fast any of these outlets is reached.  Ten "
      + "per cent ammonia in air at 700 K burns to nitrogen at equilibrium; "
      + "whether a real burner gets there is kinetics, which a Gibbs reactor "
      + "does not have.",
  },
];
