//  GENERATED by gui/scripts/copyDocs.mjs from `DOCS` in docs/Makefile.
//  DO NOT EDIT.  Adding a guide to DOCS and a label to copyDocs' LABELS
//  is what puts it in the Help menu; there is no second list to update,
//  which is the whole point -- see check_guide_menu.py.

export const GUIDES = [
    { name: "userGuide", label: "User Guide" },
    { name: "developerGuide", label: "Developer Guide" },
    { name: "theoryGuide", label: "Theory Guide" },
    { name: "propsGuide", label: "Props Workflow Guide" },
    { name: "eduToolsGuide", label: "EduTools Guide" },
    { name: "designGuide", label: "Process Design Heuristics" },
    { name: "explorerGuide", label: "Explorer Guide" },
    { name: "tutorialsGuide", label: "Tutorials Guide" },
] as const;

export type GuideName = (typeof GUIDES)[number]["name"];
